version: '3.7'
services:
  crusader-db:
    container_name: crusader-db
    image: mongo:5.0.6
    ports:
      - 27017:27017
    volumes:
      - .dbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - crusader-network

  mongo-express:
    depends_on: [crusader-db]
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@crusader-db:27017/
    networks:
      - crusader-network

  crusader-app:
    build:
      dockerfile: Dockerfile
    image: crusader-app:latest
    container_name: crusader-app
    restart: always
    ports:
      - 8080:8080
    depends_on: [crusader-db]
    networks:
      - crusader-network

networks:
  crusader-network:
    driver: bridge